[32m[0114 18:25:50 @logger.py:70][0m Argv: cifar10-densenet.py
[32m[0114 18:25:50 @utils.py:98][0m TENSORPACK_DATASET not set, using /home/per-andre/Projects/tensorpack/tensorpack/dataflow/dataset for dataset.
[32m[0114 18:25:50 @cifar.py:34][0m Found cifar10 data in /home/per-andre/Projects/tensorpack/tensorpack/dataflow/dataset/cifar10_data.
